import Head from 'next/head'
import Image from 'next/image'
import FrontPage from '../components/FrontPage'
import About from '../components/About'
import Menu from '../components/Menu'
import Footer from '../components/Footer'
import Data from '../components/Data'

import dynamic from "next/dynamic"

const Header = dynamic(()=>import('../components/Header'),{ssr: false})

export default function Home() {
  // console.log(data)
  return (
    <div>
      <Head>
        <title>Pizzoo App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <FrontPage />
      <About />
      <Menu data={Data}/>
      <Footer />
    </div>
  )
}

// export async function getServerSideProps(context) {
//   const res = await fetch(`https://run.mocky.io/v3/ec196a02-aaf4-4c91-8f54-21e72f241b68`)
//   const data = await res.json()

//   // Pass data to the page via props
//   return { props: { data } }
// }
